### PR TITLE
Autocomplete Functionality for Map Search Bar

### PR DESCRIPTION
**Pull request by michaelgoldfish**
The google maps search bar now has autocomplete when searching for the destination. There isn't logic connected to the search bar so the results don't affect the map.

### CODE REVIEW

**Review by zephix109 — COMMENTED** [review]
Do we not need the google maps api key in the index.html file? I thought that was where the credentials needed to be stored for the map to communicate properly with google servers

**Comment by alphakennyn** [comment]
Yea, I did find it weird that you removed the Api key. Is there a reason behind this?

**Comment by michaelgoldfish** [comment]
I was wondering this too honestly, but all the research Eric and I did blamed the cause of the error we were getting (I believe it was "a.getAttribute is not a defined function") on how the places library of googlemaps was being added. The change in index.html was the solution we found (plus we had to remove "api;" from the src string as well) and for whatever reason it's now working. We can try re-adding the key again but we were getting angry messages in the console.

**Review by zephix109 — APPROVED** [review]
This addition doesn't break any functionality so let's keep note of it and merge the new feature

**Pull request merged**
