### PR TITLE
Changed map layout and added search bar

### PR DESCRIPTION
**Pull request by alphakennyn**

### CODE REVIEW

**Review by zephix109 — COMMENTED** [review]
The initial page displayed has been changed to the app.html instead of home.html, have all of the respective files been updated to reflect that change?

**Review by zephix109 — COMMENTED** [review]
Why didn't we use smart commits for these changes?

**Comment by alphakennyn** [comment]
@zephix109 There were no User stories directly linked to the small features, so I didn't think it was worth smart committing to Efficient Path Issue or any other Issues.

**Comment by michaelgoldfish** [comment]
How come we switched from "home" to "app" for the language features?

**Comment by zephix109** [comment]
Fair enough. Next time add smart commits for the user story it most closely resembles. And I made a mistake, your removal of code from the home.html was just to add in the sidebar. I saw it once I ran it.

**Review by zephix109 — APPROVED** [review]
Merging into dev and retesting. Will add any new bugs that show up.

**Comment by alphakennyn** [comment]
@michaelgoldfish I forgot to mention, I added a side-menu to avoid clustered.  This also includes the language option. 

Everything in the side menu is now in app file

**Pull request merged**
