### PR TITLE
Functional drawn path onto Map

### PR DESCRIPTION
**Pull request by alphakennyn**
Includes:
- Display 10 nearest bus stops to clicked location
-Bus stops are displayed in black and selected bus stops are chagned to navy
-double-clicking the busstop will draw the path from user's location to selected bus-stop

### CODE REVIEW

**Review by zephix109 — COMMENTED** [review]
So we no longer need google maps native plugin for this feature? Does this mean we no longer need to install the plugin locally with the google authentication key?

**Comment by alphakennyn** [comment]
@zephix109 No, we're using JS google map which is lighter for the app as we're calling from google website. Native is also very limited for our project thus we had hit a wall. The JS google map opens more doors.

Since we're calling the google map from google website, we no longer need to install any packages.

**Review by Theebz95 — COMMENTED** [review]
With the removal of the stop_init service where has the observer service been moved to?

**Comment by alphakennyn** [comment]
@Theebz95 All map functionalities are placed into providers/GoogleMaps.ts

**Review by zephix109 — APPROVED** [review]
Code created through pair programming. Functionality and formatting approved.

**Pull request merged**
