### PR TITLE
Implemented Server folder and backend functionality

### PR DESCRIPTION
**Pull request by alphakennyn**

### CODE REVIEW

**Review by zephix109 — COMMENTED** [review]
So all of the js files are our controllers for communicating with the database?

**Review by zephix109 — COMMENTED** [review]
Commented out code will be removed when full implementation is ready and everything is pulled into master

**Review by zephix109 — COMMENTED** [review]
Thank you for adding readme information about installation

**Comment by alphakennyn** [comment]
We are using NodeJS for our back-end to post and get from our db.  Additionally, we create route functions (found in route.js) that will be called from our app. These routes call our controller functions

**Review by zephix109 — APPROVED** [review]
NodeJS implementation works properly

**Pull request merged**
